/**
 * Všeobecné obchodné podmienky NEOSHIP s.r.o.
 * Verbatim prepis dokumentu platného a účinného od 14.5.2026.
 */

export type VopArticle = {
  heading: string;
  items: string[];
};

export const vopEffectiveFrom = '14.5.2026';

export const vopArticles: VopArticle[] = [
  {
    heading: '1. VŠEOBECNÉ USTANOVENIA',
    items: [
      '1.1. Všeobecné obchodné podmienky upravujú právne vzťahy vznikajúce medzi obstarávateľom a objednávateľom pri obstaraní vnútroštátnej alebo medzinárodnej prepravy zásielok prostredníctvom softvérovej aplikácie dostupnej na internetovej stránke www.aplikacia.neoship.sk (ďalej len „VOP“) a vzťahujú sa na zmluvy uzatvorené medzi obstarávateľom a objednávateľom.',
      '1.2. Na účely týchto VOP sa rozumie:',
      '1.2.1. Obstarávateľom spoločnosť NEOSHIP s.r.o., so sídlom: Miletičova 23, 821 09 Bratislava - mestská časť Ružinov, IČO: 50 286 820, zapísaná v obchodnom registri Okresného súdu v Žiline, odd.: Sro, vložka č. 65476/L, bankové spojenie: Tatra banka, a.s., IBAN: SK2911000000002948022430, ktorá je prevádzkovateľom on-line expedičného systému NEOSHIP;',
      '1.2.2. Objednávateľom fyzická osoba alebo právnická osoba, ktorá prostredníctvom služby NEOSHIP v rámci klientskej zóny a zriadeného klientského účtu na internetovej stránke www.aplikácia.neoship.sk zadá a objedná obstaranie vnútroštátnej alebo medzinárodnej prepravy zásielky/zásielok obstarávateľom v súlade s týmito VOP;',
      '1.2.3. Prepravcom je spoločnosť uvedená v bode 2.3. týchto VOP poskytujúca kuriérske služby a realizujúca doručovanie zásielok zadaných objednávateľom do internetového expedičného systému NEOSHIP, prostredníctvom ktorého zabezpečuje obstarávateľ prepravu;',
      '1.2.4. Neoship je softvérová aplikácia dostupná na stránke www.aplikacia.neoship.sk určená na elektronické on-line spracovávanie zásielok zadaných do systému objednávateľom a na transportovanie údajov o zásielke priamo do systému prepravcu za účelom obstarania prepravy zadaných zásielok;',
      '1.2.5. Internetovou stránkou je stránka www.aplikacia.neoship.sk na ktorej obstarávateľ prevádzkuje služby expedičného systému Neoship, určeného na obstaranie prepravy zásielok;',
      '1.2.6. Zásielkou je vec alebo súbor vecí určených objednávateľom na prepravu z konkrétneho miesta (miesta odoslania) k označenému príjemcovi zásielky do miesta určenia (miesta dodania). Objednávateľ špecifikuje druh zásielky, vyberie a označí spôsob a požadovaný čas prepravy zásielky;',
      '1.2.7. Zmluvou je servisná zmluva o obstaraní vnútroštátnej alebo medzinárodnej prepravy zásielok v rámci systému Neoship uzatvorená v súlade s týmito VOP medzi obstarávateľom a objednávateľom;',
      '1.2.8. Kreditovým účtom je účet identifikovaný jedinečným číselným označením zriadený obstarávateľom pre objednávateľa v rámci jeho klientského účtu pri využívaní on-line expedičného systému Neoship, na ktorý bude objednávateľ uhrádzať zálohy na budúce obstarania prepravy zásielok identifikované prostredníctvom priradeného číselného označenia, a z ktorého sa budú zároveň uhrádzať ceny za jednotlivé obstarania prepravy.',
      '1.2.9. Osobnými údajmi – údaje týkajúce sa fyzickej alebo právnickej osoby (ďalej už len ako „dotknuté osoby“), ktorú možno identifikovať priamo alebo nepriamo, najmä na základe všeobecne použiteľného identifikátora alebo iného identifikátora, ako je napríklad meno a priezvisko, obchodné meno, bydlisko, sídlo, dátum narodenia, rodné číslo, IČO, DIČ, telefónne číslo, email, lokalizačné údaje alebo online identifikátor (IP adresa, cookies, prihlasovacie údaje do online služieb.',
      '1.2.10 Obstaranie prepravy – preprava sa považuje za obstaranú v momente, kedy sa ku dátam o zásielke vytvoreným používateľom v jeho klientskom účte priradí sledovacie číslo prepravcu. Zároveň sa objednávateľovi vygeneruje prepravný štítok ku balíku s týmto sledovacím číslom.',
      '1.2.11. Cenník obstarávateľa – dokument obstarávateľa, v ktorom sú obsiahnuté všetky poplatky obstarávateľa súvisiace s využívaním jeho služieb, zabezpečovaním technickej podpory a softvérovej aktualizácie, vrátane platieb za jednotlivé služby a rozsah funkcionality poskytované obstarávateľom prostredníctvom Neoshipu. Aktuálny cenník obstarávateľa je zverejnený a dostupný na internetovej stránke www.neoship.sk ako aj priamo v aplikácii Neoship. Jednotlivé poplatky a platby za služby sa strhávajú buď priamo z kreditového účtu objednavateľa alebo budú individuálne odfakturované objednávateľovi mimo kreditového účtu. Tieto faktúry je objednávateľ povinný uhradiť priamo obstarávateľovi mimo kreditového účtu.',
      '1.2.12 Aktivačný poplatok – jednorazový poplatok za zriadenie klientského a kreditového účtu, zabezpečenie technického prepojenia s ostatnými systémami obstarávateľa a objednávateľa. Tento poplatok je účtovaný aj v prípade preregistrácie Objednávateľa (zmena s.r.o., IČO, a pod.)',
      '1.2.13 Mesačný poplatok – zahŕňa technickú podporu, údržbu a aktualizáciu systému Neoship a súvisiacich systémov a prepojení.',
      '1.2.14 Poplatok za obstaranie prepravy zásielok – za obstaranie prepravy každej jednej zásielky prostredníctvom služby Neoship má Obstarávateľ nárok na cenu určenú na základe Cenníka obstarania prepravy.',
      '1.3. Tieto VOP vymedzujú a upresňujú základné práva a povinnosti zmluvných strán pri uzatváraní zmluvy prostredníctvom registračného formulára alebo pri uzatvorení písomných zmlúv prostredníctvom obchodného zástupcu. Obstarávateľ sa zaväzuje obstarať vnútroštátnu alebo medzinárodnú prepravu zásielok objednávateľovi a objednávateľ sa zaväzuje uhradiť obstarávateľovi za využívanie jeho služieb dohodnutú odmenu vo výške uvedenej v aktuálnom cenníku obstarávateľa alebo vo výške tak, ako bude táto dojednaná v uzatvorenej individuálnej zmluve medzi nimi.',
      '1.4. Ustanovenia VOP sú neoddeliteľnou súčasťou zmluvy a sú vždy dostupné v rámci zriadeného klientského účtu objednávateľa. Odlišné ustanovenia od ustanovení týchto VOP je možné dohodnúť pri uzatvorení zmluvy. Takto dojednané odlišné ustanovenia v zmluve majú prednosť pred ustanoveniami týchto VOP. Znenie VOP je obstarávateľ oprávnený meniť alebo dopĺňať. Práva a povinnosti zmluvných strán sa riadia vždy aktuálnym znením obchodných podmienok, ktoré budú objednávateľovi oznámené dostatočne včas, najneskôr však týždeň pred vstupom do platnosti, a to buď prostredníctvom emailu alebo elektronickej správy dostupnej v klientskom účte. V prípade nesúhlasu objednávateľa s aktuálnym znením VOP, má právo od zmluvy odstúpiť. Práva a povinnosti zmluvných strán sa ďalej riadia podmienkami užívania klientského účtu zriadeného na internetovej stránke a podmienkami a pokynmi uvedenými v rámci klientského účtu a jeho funkcionalít.',
    ],
  },
  {
    heading: '2. ELEKTRONICKÁ ŽIADOSŤ (REGISTRÁCIA) A UZATVORENIE ZMLUVY',
    items: [
      '2.1. Na základe deklarovaného záujmu objednávateľa o využívanie služby Neoship (telefonicky, emailom, online formulárom, osobne) bude objednávateľovi zo strany obstarávateľa zaslaný registračný formulár spolu s návrhom na uzatvorenie servisnej zmluvy a podmienkami využívania internetovej služby Neoship vrátane cenovej ponuky a týchto VOP, s ktorými je objednávateľ povinný sa riadne oboznámiť. Po vyplnení a odoslaní registračného formulára je objednávateľ povinný uhradiť aktivačný poplatok, na základe elektronickej faktúry zaslanej obstarávateľom na emailovú adresu zadanú objednávateľom v registračnom formulári. Odoslaním registračného formulára a súčasne pripísaním úhrady aktivačného poplatku na bankový účet obstarávateľa, objednávateľ vyslovuje bezvýhradný súhlas s VOP obstarávateľa. Zároveň vyjadruje súhlas s jeho cenníkom resp. individuálnou cenovou ponukou a podmienkami využívania online expedičného systému Neoship. Objednávateľ je v rámci registračného formulára povinný uviesť a vyplniť všetky požadované údaje, vrátane kontaktných údajov na štatutára objednávateľa, resp. osobu oprávnenú konať v mene objednávateľa ako aj ďalšie zodpovedné osoby, ktoré budú mať prístup do užívateľského účtu v rámci systému Neoship a zadať email, na ktorý budú zaslané prístupové údaje. V prípade ak je objednávateľ fyzickou osobou je povinný potvrdiť údaj o tom, že má minimálne 18 rokov. Bez potvrdenia údaju o zodpovedajúcom veku obstarávateľ nebude akceptovať vyplnený registračný formulár. Údaje uvádzané v registračnom formulári musia byť pravdivé a úplné.',
      '2.2. Obstarávateľ bude považovať potvrdenie návrhu na uzavretie zmluvy za neúplné a nebude naň prihliadať, ak:',
      '2.2.1. v registračnom formulári objednávateľ nevyplní všetky povinné a požadované údaje podľa bodu 2.1. týchto VOP, vrátane veku objednávateľa;',
      '2.2.2. v registračnom formulári objednávateľ nevyznačí, že bez výhrad súhlasí s týmito VOP v súlade s bodom 2.1. týchto VOP;',
      '2.2.3. v registračnom formulári objednávateľ uvedie neúplné alebo nepravdivé údaje.',
      '2.2.4. objednávateľ neuhradí aktivačný poplatok na základe obstarávateľom zaslanej elektronickej faktúry podľa bodu 2.1.',
      '2.3. Objednávateľ vyplnením a odoslaním registračného formulára a súčasne úhradou aktivačného poplatku berie na vedomie, že ním zadávaná vnútroštátna alebo medzinárodná preprava bude zabezpečovaná prostredníctvom zvolených prepravcov, ktorými môžu byť spoločnosti:',
      'a) Slovak Parcel Service, s.r.o. so sídlom: Senecká cesta 1, 900 28 Ivanka pri Dunaji, IČO: 31 329 217 zapísaná v Obchodnom registri Okresného súdu Bratislava I., oddiel Sro, vložka č. 3215/B',
      'b) EXPRESS ONE SLOVAKIA, s.r.o., so sídlom: Senecká cesta 1, 900 28 Ivanka pri Dunaji, IČO: 31 342 621, zapísaná v Obchodnom registri Okresného súdu Bratislava I., oddiel Sro, vložka č. 4376/B',
      'c) GLS General Logistics Systems Slovakia s.r.o. so sídlom Budča 1039, 96233 Budča, IČO: 36 624 942, zapísaná v Obchodnom registri Okresného súdu Banská Bystrica, oddiel Sro, vložka č. 9084/S',
      'd) Packeta Slovakia s. r. o., so sídlom: Sliačska 1E, 831 02 Bratislava – mestská časť Nové Mesto, IČO: 48 136 999 zapísaná v Obchodnom registri Okresného súdu Bratislava I., oddiel Sro, vložka č. 105158/B.',
      'e) Direct Parcel Distribution SK s.r.o., so sídlom Technická 7, 821 04 Bratislava, IČO: 35 834 498, zapísaná v Obchodnom registri Okresného súdu Bratislava I., oddiel Sro, vložka č. 26367/B',
      'f) Slovenská pošta, a.s., so sídlom Partizánska cesta 9, 975 99, Banská Bystrica, IČO: 36 631 124, zapísaná v Obchodnom registri Okresného súdu Banská Bystrica, oddiel Sa, vložka č. 803/S',
      'Obstarávateľ má uzatvorenú osobitnú zmluvu o spolupráci s vyššie uvedenými prepravcami, pričom nie je vylúčená ani budúca spolupráca s inými prepravcami. V takom prípade bude mať objednávateľ možnosť výberu prepravcu pri zadávaní zásielok do systému Neoship.',
      '2.4. Objednávateľ berie na vedomie, že preprava vnútroštátnych zásielok sa spravuje obchodnými a prepravnými podmienkami vnútroštátnej prepravy prepravcu a preprava medzinárodných zásielok sa spravuje prepravnými podmienkami medzinárodnej prepravy prepravcu. Prepravné podmienky prepravcu sú dostupné v aplikácii Neoship v časti dokumenty.',
      '2.5. Obstarávateľ zvyčajne do 7 pracovných dní od obdržania riadne vyplneného registračného formulára a pripísania celej výšky aktivačného poplatku na účet obstrarávateľa, zriadi objednávateľovi v rámci služby Neoship klientský účet, ktorého súčasťou bude kreditový účet identifikovaný jedinečným číselným označením. Obstarávateľ zašle objednávateľovi na email v zmysle bodu 2.1 tohto článku VOP prihlasovacie (prístupové) údaje k zriadenému klientskému účtu. Prístupové údaje do užívateľského účtu je objednávateľ povinný uchovávať v tajnosti, chrániť a podniknúť všetky kroky k tomu, aby nedošlo k ich zneužitiu alebo strate. Objednávateľ je oprávnený tieto údaje sprístupniť len ním označeným osobám v registračnom formulári a je zodpovedný za poskytnutie prihlasovacích údajov ďalším ním neoznačeným osobám, alebo tretím osobám pre prípad ich zneužitia.',
      '2.6. Spolu s prihlasovacími údajmi obstarávateľ sprístupní objednávateľovi aj využívanie prenosu dát cez API, pričom pri využívaní tohto prenosu dát sa musí objednávateľ riadiť podľa pravidiel a pokynov obstarávateľa.',
      '2.7. Objednávateľ je uzrozumený s tým, že po aktivovaní klientského účtu dôjde k vytvoreniu dátového prepojenia medzi klientským účtom objednávateľa zriadeným v systéme Neoship a systémami prepravcu pre evidenciu a spracovávanie zásielok. Objednávateľ berie na vedomie, že vo vzťahu k prepravcovi vystupuje vo vlastnom mene a na vlastný účet. Obstarávateľ je povinný výhradne obstarať prepravu zásielok pre objednávateľa prepravcom, neplní však funkciu sprostredkovateľa, nezastupuje objednávateľa a nekoná v súvislosti s prepravou na účet objednávateľa. Obstarávateľ má právo zrušiť klientský účet objednávateľa bez náhrady škody alebo ušlého zisku, ak dochádza prostredníctvom klientského účtu objednávateľa k porušovaniu dobrých mravov, platných právnych predpisov alebo týchto VOP.',
    ],
  },
  {
    heading: '3. OBJEDNÁVKA SLUŽIEB A OBSTARANIE PREPRAVY',
    items: [
      '3.1. Objednávateľ prostredníctvom svojho klientského účtu zadá do systému Neoship povinné a prípadne preferované údaje o zásielkach, ktorých preprava má byť obstaraná.',
      '3.2. Obstarávateľ zabezpečuje prenos údajov a dát týkajúcich sa zadaných zásielok do systému prepravcu. Obstarávateľ nezodpovedá za správnosť údajov poskytovaných/zadávaných do systému zo strany prepravcu ani za správnosť údajov zadávaných do systému zo strany zodpovedných osôb určených objednávateľom. Obstarávateľ nezodpovedá za prípadnú škodu alebo ušlý zisk, ktorý by objednávateľovi vznikol v dôsledku takto nesprávne, neúplne alebo nepresne zadaných údajov. Objednávateľ výlučne sám zodpovedá za správnosť implementácie dátového prepojenia cez API a efektívnu implementáciu exportov/importov, rovnako aj za správnosť údajov poskytnutých prepravcovi. Ak po zadaní údajov do systému objednávateľ zistí chybu alebo zadá nesprávne, neúplné alebo neurčité údaje, rieši takto vzniknutú situáciu priamo s prepravcom, rovnako tak objednávateľ s prepravcom samostatne rieši aj prípadné reklamácie súvisiace s doručovaním zásielok a pod..',
      '3.3. Obstarávateľ je povinný obstarať prepravu zásielky po zadaní elektronickej objednávky podľa bodu 3.1. tohto článku VOP najneskôr nasledujúci pracovný deň po jej vyžiadaní. Za vyžiadanie sa považuje kliknutie na tlačidlo určené pre tlač prepravných štítkov ku balíkom, ku ktorým má byť preprava obstaraná. Za obstaranú prepravu sa považuje to, ak ku zásielke vytvorenej používateľom podľa bodu 3.1. týchto VOP, je priradené sledovacie číslo zo systému prepravcu. Zároveň sa objednávateľovi vygeneruje prepravný štítok ku balíku s týmto sledovacím číslom. Spôsob a čas vyzdvihovania zásielok si dohodne individuálne objednávateľ s prepravcom. Objednávateľ si je vedomý, že kritériá pre balenie zásielok ako aj ďalšie náležitosti súvisiace s prepravou zásielok sa riadia prepravnými podmienkami daného prepravcu, tak ako je uvedené v bode 2.4. týchto VOP. V prípade ak tieto podmienky objednávateľ poruší, zodpovedá tak v plnom rozsahu za vzniknutú škodu.',
      '3.4. Objednávateľ berie na vedomie a súhlasí s tým, že súčasťou systému Neoship sú aj iné funkcionality, ktoré využívajú systémy a služby tretích strán. Objednávateľ môže funkcionality poskytované v rámci systému Neoship využívať aj na marketingové aktivity a prieskumy. Za účelom získania súhlasu dotknutých osôb so spracovaním ich osobných údajov na marketingové účely, je objednávateľ povinný pri každej a jednej dotknutej osobe vyznačiť, či udelila výslovný súhlas so spracovaním jej osobných údajov na tieto účely, prípadne či tento súhlas odvolala alebo neudelila vôbec. O týchto skutočnostiach je objednávateľ povinný bezprostredne informovať obstarávateľa, prípadne tieto informácie zadať priamo do systému Neoship. Bez ohľadu na dôvod, ak pri zásielke alebo na inom mieste nebude definovaný jednoznačný súhlas dotknutej osoby so spracovaním jej osobných údajov pre marketingové a prieskumné účely, obstarávateľ nesmie osobné údaje tejto dotknutej osoby na tieto účely použiť.',
    ],
  },
  {
    heading: '4. CENA ZA SLUŽBY, OBSTARANIE PREPRAVY A PLATOBNÉ PODMIENKY',
    items: [
      '4.1. Obstarávateľ má nárok na odmenu za jeho služby a obstaranie prepravy zásielok prostredníctvom systému Neoship. Objednávateľ je túto odmenu povinný uhradiť spôsobom a za podmienok uvedených v týchto VOP a v cenníku obstarávateľa. Cena za služby, poplatky a obstaranie prepravy pre jednotlivé balíky je uvedená v aktuálnom cenníku obstarávateľa dostupnom na jeho webovej stránke www.neoship.sk resp. v rámci klientského účtu používateľa alebo vždy vopred dohodnutá a zaevidovaná v dodatku ku zmluve s objednávateľom na základe predpokladaného a deklarovaného počtu zásielok, ktorých počet je uvedený tiež v aktuálnom dodatku ku zmluve. Objednávateľ berie na vedomie, že spôsob výpočtu cien niektorých doplnkových služieb a poplatkov a aj ich prisudzovanie ku obstaraným zásielkam sa riadi kritériami jednotlivých prepravcov. Zároveň sa u jednotlivých prepravcov môžu líšiť. Všetky tieto kritériá sú uvedené vo VOP jednotlivých prepravcov, ktoré má objednávateľ k dispozícii aj v rámci jeho klientskeho prístupu v Neoshipe.',
      '4.2. Obstarávateľ je oprávnený v rámci ponuky služieb poskytnúť zľavu z poplatkov v prípade tzv. propagovanej „akcie“ ponúkaných služieb, ktorá môže byť časovo limitovaná. Obstarávateľ je zároveň oprávnený poskytnúť objednávateľovi individuálnu zľavu za individuálne dohodnutých podmienok, ktoré budú upravené v zmluve, resp. dodatkom k zmluve. Pokiaľ v zmluve takéto individuálne dojednanie absentuje, je objednávateľ povinný uhrádzať jednotlivé poplatky a ceny služieb podľa aktuálneho cenníka obstarávateľa.',
      '4.3. Obstarávateľ je oprávnený jednostranne zmeniť cenu za obstaranie prepravy dohodnutú podľa bodu 4.1 týchto VOP ak si objednávateľ v predchádzajúcich 12 kalendárnych mesiacoch u obstarávateľa objedná obstaranie prepravy zásielok o menej ako 20% než pôvodne deklaroval, najviac však o 50% z ceny za obstaranie prepravy podľa cenníka. V záujme zachovania kvality služieb je obstarávateľ rovnako oprávnený jednostranne upravovať ceny služieb a to predovšetkým v situácií kedy mu najmä vplyvom tretích strán (legislatívne opatrenia, dodávatelia služieb, prepravcovia) narástli finančné náklady súvisiace s prevádzkovaním služieb Neoship. O zmene ceny bude objednávateľ informovaný dostatočne včas, najneskôr však týždeň pred vstupom do platnosti a to prostredníctvom emailu alebo elektronickou správou dostupnou v jeho klientskom účte. Pokiaľ so zmenou ceny objednávateľ nesúhlasí má možnosť od zmluvy v stanovenej lehote podľa bodu 7.2.4. VOP odstúpiť. Ak v uvedenej lehote objednávateľ neodstúpi má sa za to, že so zmenou ceny súhlasí.',
      '4.4. Konečná cena za obstaranie prepravy bude určená až po obstaraní prepravy zásielok pre objednávateľa, a to na základe objednávateľom využívanej verzie funkcionality v Neoshipe, zvolených doplnkových služieb, služieb priradených ku zásielke prepravcom pri jej spracovaní a skutočnej hmotnosti zásielky, ktorej preprava sa obstarala. Informácia o cene za obstaranie prepravy a stav kreditového účtu budú vždy uvedené priamo v klientskom účte objednávateľa zriadenom v systéme Neoship.',
      '4.5. Cenu za obstaranie prepravy a poplatky bude objednávateľ primárne uhrádzať prostredníctvom kreditného účtu zriadeného v rámci služby Neoship, a to pod variabilným symbolom zhodným s jedinečným číselným označením priradeným konkrétnemu kreditovému účtu. Spôsob úhrady kreditu a ceny za obstaranie si môžu objednávateľ a obstarávateľ dohodnúť odlišne v servisnej zmluve. Zároveň v určitých prípadoch môže obstarávateľ vystaviť objednávateľovi faktúru za služby mimo kreditového účtu. Tieto faktúry je objednávateľ povinný uhradiť priamo obstarávateľovi mimo kreditového účtu.',
      '4.6. Objednávateľom predplatený kredit tvorí zálohu na budúce prípady obstarania prepravy zásielok obstarávateľom pre objednávateľa a zároveň aj niektoré poplatky obstarávateľa. Minimálna výška zálohy pre tvorbu záznamov o zásielkach v Neoshipe je stanovená vo výške 0,01 Eur s DPH. Minimálna výška zálohy pre obstaranie prepravy zásielok a teda s tým spojenú tlač prepravných štítkov je stanovená vo výške 30,01 Eur s DPH pri verzii Prémium a 25,07 € s DPH pri verzii Základ. Obstarávateľ podľa evidencie počtu obstaraných zásielok objednávateľa a dát podľa bodu 4.4 tohto článku VOP, vystaví účtovný doklad - elektronickú faktúru za poskytnuté služby v danom kalendárnom mesiaci vo formáte pdf, a to vždy ku koncu príslušného kalendárneho mesiaca a odošle ju najneskôr do 15 tich kalendárnych dní objednávateľovi na ním zadaný mail v registračnom formulári. Elektronická faktúra je plnohodnotný daňový doklad.',
      '4.7. Obstarávateľ má právo na čerpanie objednávateľom predplateného kreditu z jeho kreditového účtu, a to v rozsahu vystavenej faktúry podľa bodu 4.6 a 4.8. týchto VOP, s čím objednávateľ bez výhrad súhlasí a je s tým uzrozumený.',
      '4.8. Objednávateľ je na základe servisnej zmluvy oprávnený objednať si budúce obstaranie prepravy zásielok obstarávateľom a predplatiť si kredit podľa bodu 4.6 VOP aj opakovane, prípadne na dlhšie časové obdobie, napr. na celý kalendárny rok. Objednávateľ je oprávnený kedykoľvek kontrolovať stav predplateného kreditu, ako aj spotrebu kreditu a zároveň je oprávnený požadovať vyhotovenie výpisu z kreditového účtu za ním zvolené časové obdobie, a to prostredníctvom klientskej zóny internetovej stránky www.aplikacia.neoship.sk. Objednávateľ je povinný udržiavať kreditový účet v takej výške, ktorá v záujme predchádzania debetnému stavu s najväčšou pravdepodobnosťou pokryje náklady na ním požadované obstaranie prepráv jednotlivých zásielok. Z tohto dôvodu sa vo verzii Prémium adekvátna výška kreditu potrebného pre vygenerovanie prepravných štítkov a následné obstaranie prepravy vypočítava podľa vzorca (počet štítkov x 5,00 € s DPH + 25 € s DPH) < aktuálny stav kreditu. Vo verzii Základ sa adekvátna výška kreditu potrebného pre vygenerovanie prepravných štítkov a následné obstaranie prepravy vypočítava podľa vzorca (počet štítkov x 0,06 € s DPH + 25 € s DPH) < aktuálny stav kreditu. V prípade, ak výška kreditového účtu bude nedostatočná, generovanie prepravných štítkov nebude možné, kým sa kreditový účet nedoplní na sumu dostatočne vysokú pre generovanie požadovaného počtu štítkov podľa vzorca vyššie. Z dôvodu nedostatočnej výšky kreditu pre generovanie štítkov, a teda objednanie obstarania prepravy objednávateľom, obstarávateľ nezodpovedá za prípadný ušlý zisk objednávateľa alebo za náhradu škody, ktorá by objednávateľovi vznikla v dôsledku pozastavenia generovania prepravných štítkov. A to až do času navýšenia stavu kreditového účtu objednávateľom na dostatočnú úroveň.',
      '4.9. Ak poplatky za služby sťahované z kreditového účtu objednávateľa a objednávky objednávateľa na obstaranie prepravy zásielok obstarávateľom prekročia sumu objednávateľom predplateného kreditu, objednávateľ je povinný zaplatiť vzniknutý dlh na kreditovom účte najneskôr do obdobia splatnosti, uvedenom na najbližšej faktúre vystavenej po dni kedy došlo ku vzniku dlhu. Až do zaplatenia dlhu na kreditovom účte podľa tohto bodu VOP nebude objednávateľ oprávnený vykonávať nové objednávky obstarania prepravy. Obstarávateľ tak nezodpovedá za prípadný ušlý zisk objednávateľa alebo za náhradu škody, ktorá by objednávateľovi vznikla v dôsledku neprijatia ďalších objednávok, ktoré budú pozastavené až do času vyrovnania dlhu na kreditovom účte a uhradenia novej výšky zvoleného kreditu. Ak má objednávateľ záujem meniť alebo realizovať iné úkony týkajúce sa výšky kreditu na jeho účte, je potrebná písomná (emailová) žiadosť zo strany štatutárneho orgánu objednávateľa, resp. osoby oprávnenej konať v mene objednávateľa, ktorá je označená v servisnej zmluve. Za účelom potvrdenia zmeny je obstarávateľ oprávnený kontaktovať osoby označené v servisnej zmluve ako osoby oprávnené a vyžiadať si potvrdenie tejto zmeny.',
    ],
  },
  {
    heading: '5. PRÁVA, POVINNOSTI, VYHLÁSENIA A ZODPOVEDNOSŤ ZMLUVNÝCH STRÁN',
    items: [
      '5.1. Objednávateľ je oprávnený používať softvérovú aplikáciu Neoship a jej ďalšie funkcionality výhradne v rozsahu dojednanom v týchto VOP a dbať na to, aby účel jej použitia bol v súlade so zákonom, licenčnými podmienkami, inými všeobecne záväznými právnymi predpismi platnými v Slovenskej republike a dobrými mravmi, ako aj na to, aby použitím on-line expedičného systému Neoship nevznikla tretím osobám škoda alebo iná ujma na ich majetku alebo právach. Objednávateľ je ďalej oprávnený vykonávať všetky práva, ktoré mu priznáva servisná zmluva alebo tieto VOP, a to predovšetkým komunikovať priamo s prepravcom a dohodovať osobitné podmienky dopravy vo vzťahu k vyzdvihnutiu, preprave a reklamácii zásielok; využívať dostupné informácie od prepravcu o stave zásielky a pod.',
      '5.2. Objednávateľ je povinný dodržiavať a zabezpečiť splnenie povinností vyplývajúcich mu z týchto VOP. Objednávateľ je ďalej povinný reklamovať vady v preprave písomne priamo u prepravcu. Ak po zadaní údajov do systému objednávateľ zistí chybu alebo zadá nesprávne, neúplné alebo neurčité údaje, rieši takto vzniknutú situáciu po spracovaní zásielok prepravcom priamo s ním a to primárne prostredníctvom funkcionality na to určenej v Neoshipe. Rovnako tak objednávateľ rieši s prepravcom aj prípadné reklamácie súvisiace s doručovaním zásielok a pod.. Pred spracovaním zásielok prepravcom rieši objednávateľ prípadné požiadavky s obstarávateľom.',
      '5.3. Objednávateľ má právo požadovať nárok na náhradu škody od obstarávateľa v prípade, ak obstarávateľ poruší svoje povinnosti vyplývajúce mu zo servisnej zmluvy a neobstará zadanú prepravu. Objednávateľovi bude vrátená cena za obstaranie prepravy pre prípad riadne uplatnenej a uznanej reklamácie zo strany prepravcu. Obstarávateľ je v takomto prípade povinný vrátiť uhradenú cenu obstaranej prepravy objednávateľovi v lehote do 15 dní od obdržania oznámenia prepravcu o uznaní oprávnenej reklamácie. Objednávateľ berie na vedomie, že:',
      'a) za riadne a včasné doručenie zásielky, ktorej preprava bola obstaraná obstarávateľom, zodpovedá výhradne prepravca;',
      'b) prepravca zodpovedá za škodu spôsobenú na zásielke od okamihu jej odovzdania osobe poverenej vykonaním prepravy prepravcom až do jej odovzdania adresátovi zásielky.',
      '5.4. Obstarávateľ ani prepravca nezodpovedá za škody na zásielke spôsobené:',
      '5.4.1. objednávateľom, adresátom alebo vlastníkom zásielky alebo ich nevhodnými pokynmi;',
      '5.4.2. vadou alebo prirodzenou povahou obsahu zásielky;',
      '5.4.3. nevhodným obalom alebo spôsobom vystuženia a balenia, ktorým objednávateľ vybavil zásielku na prepravu, prípadne vadným obalom zásielky.',
      '5.5. Obstarávateľ vyhlasuje a zodpovedá za to:',
      'a) že softvérová aplikácia, na použitie ktorej bola objednávateľovi udelená licencia je v súlade so zákonom a inými všeobecne záväznými právnymi predpismi platnými v Slovenskej republike, žiadnym spôsobom neporušuje autorské práva ani iné práva a oprávnené záujmy tretích osôb a je riadne použiteľná a funkčná na účely užívania on-line expedičného systému a systému API;',
      'b) za 97%-nú dostupnosť služby Neoship. To neplatí v prípade plánovaného výpadku alebo plánovanej údržby internetovej stránky www.aplikacia.neoship.sk alebo samotnej služby Neoship, ak boli oznámené objednávateľovi aspoň 24 hodín vopred.',
      '5.6. Obstarávateľ nezodpovedá za použitie:',
      'a) softvérovej aplikácie objednávateľom alebo tretími osobami, ktorým objednávateľ umožnil prístup k softvérovej aplikácii, predovšetkým za zneužitie softvérovej aplikácie alebo jej použitie v rozpore s týmito VOP, za ujmu, ktorá bude tretím osobám spôsobená použitím softvérovej aplikácie.',
      'b) za chyby a vady softvéru, ktoré vzniknú použitím softvérovej aplikácie v rozpore s licenčnými podmienkami, VOP, zákonom, inými všeobecne záväznými právnymi predpismi platnými v Slovenskej republike, sú spôsobené treťou osobou, neodvrátiteľnou udalosťou, a pod.;',
      'c) za správnosť údajov zadávaných do systému zo strany objednávateľa alebo prepravcu; poruchu spočívajúcu v znížení kvality alebo vo výpadkoch služby Neoship spôsobených objednávateľom alebo ním poverenými osobami; poruchu spôsobenú v dôsledku udalostí, ktoré majú charakter vyššej moci; poruchu spôsobenú užívaním služby Neoship; poruchu spôsobenú výpadkom, systémovou chybovu alebo technickými problémami na strane prepravcu.',
      '5.7. Obstarávateľ zodpovedá objednávateľovi za akúkoľvek poruchu, bez ohľadu na jej charakter, trvanie alebo závažnosť, len ak bola porucha spôsobená porušením povinností obstarávateľa z tejto zmluvy a zo všeobecne záväzných právnych predpisov.',
      '5.8. Objednávateľ nahlási poruchu služby Neoship obstarávateľovi bez zbytočného odkladu po tom, ako sa o nej dozvie. Poruchu je objednávateľ oprávnený nahlásiť primárne písomne emailom na adresu klientservis@neoship.sk alebo elefonicky na tel. č. +421 901 714 003. Objednávateľ je povinný pri ohlásení poruchy uviesť svoju identifikáciu a zrozumiteľný a dostatočný popis poruchy.',
      '5.9. Obstarávateľ sa zaväzuje začať s odstraňovaním poruchy do 10 hod. od jej oznámenia objednávateľom. Obstarávateľ sa zaväzuje odstrániť poruchu do 24 hod. Ak má porucha závažnejší charakter alebo ak z technických alebo personálnych dôvodov obstarávateľ nemôže poruchu v tejto lehote odstrániť, je povinný tieto informácie do 24 hod. oznámiť objednávateľovi spolu s predpokladaným termínom odstránenia poruchy. Obstarávateľ odstráni poruchu v zmysle bodu 5.9. tohto článku VOP na vlastné náklady. Ak ide o poruchu, za ktorú obstarávateľ nezodpovedá, obstarávateľ odstráni poruchu na náklady objednávateľa.',
      '5.10. Objednávateľ zodpovedá obstarávateľovi za škodu spôsobenú porušením jeho povinností.',
      '5.11. Objednávateľ je povinný utajovať údaje z databázy softvérovej aplikácie a schémy, pričom tieto databázy a schémy nie je oprávnený sprístupniť ani inak poskytnúť tretím osobám. Objednávateľ zodpovedá obstarávateľovi za škodu spôsobenú porušením tejto povinnosti.',
      '5.12. Obstarávateľ a objednávateľ sa zaväzujú, že budú zachovávať mlčanlivosť o všetkých skutočnostiach, o ktorých sa dozvedeli v súvislosti s uzatvorením servisnej zmluvy a udelením licencie na použitie softvérovej aplikácie Neoship, sprístupnením osobných údajov zadávaných do databázy, ak tieto skutočnosti môžu mať povahu obchodného tajomstva zmluvnej strany alebo je zrejmé, že zmluvná strana má záujem na ich utajení a ich utajenie zodpovedajúcim spôsobom zabezpečuje alebo táto povinnosť vyplýva zmluvným stranám priamo zo zákona.',
    ],
  },
  {
    heading: '6. SANKCIE',
    items: [
      '6.1. Ak sa objednávateľ omešká s úhradou podľa bodu 4.6 až 4.9 týchto VOP, má obstarávateľ nárok na zaplatenie zmluvnej pokuty vo výške 0,05 % z dlžnej sumy za každý deň omeškania. Tým nie je dotknutý nárok obstarávateľa na náhradu škody a úrok z omeškania určený zákonným spôsobom.',
    ],
  },
  {
    heading: '7. ZÁNIK ZMLUVY',
    items: [
      '7.1. Zmluva sa uzatvára na dobu neurčitú.',
      '7.2. Zmluva zaniká:',
      '7.2.1. písomnou dohodou zmluvných strán ku dňu uvedenému v tejto dohode;',
      '7.2.2. výpoveďou ktorejkoľvek zo zmluvných strán bez uvedenia dôvodu, pričom zmluva zaniká uplynutím 1-mesačnej výpovednej doby, ktorá začína plynúť v prvý deň kalendárneho mesiaca nasledujúceho po mesiaci, kedy bola písomná výpoveď zmluvy doručená druhej zmluvnej strane;',
      '7.2.3. odstúpením obstarávateľa od zmluvy pre podstatné porušenie povinnosti druhou zmluvnou stranou uvedených v bode 5.2 týchto VOP, pričom zmluva zaniká dňom doručenia písomného prejavu vôle o odstúpení druhej zmluvnej strane; zmluvné strany sa dohodli, že obstarávateľ je oprávnený odstúpiť od tejto zmluvy, ak sa objednávateľ omešká so splnením povinnosti zaplatiť dlh na kreditovom účte podľa bodu 4.9 VOP o viac ako 15 kalendárnych dní;',
      '7.2.4. odstúpením objednávateľa od zmluvy v prípade jeho nesúhlasu so zmenou VOP, o ktorej bol zo strany obstarávateľa upovedomený podľa bodu 1.4. týchto VOP. Odstúpenie od zmluvy musí byť písomné a musí byť zo strany objednávateľa doručené obstarávateľovi najneskôr pred účinnosťou zmeny VOP, inak sa má za to, že objednávateľ so zmenou súhlasí.',
      '7.3. Ak po zániku zmluvy eviduje obstarávateľ kladný zostatok na kreditovom účte objednávateľa, je obstarávateľ povinný zaplatiť objednávateľovi sumu zodpovedajúcu zostatku na kreditovom účte objednávateľa zníženú o zmluvnú pokutu, na ktorú vznikol obstarávateľovi nárok pred zánikom zmluvy, a to do 15 kalendárnych dní od jej zániku.',
      '7.4. Zánikom zmluvy nezaniká nárok na zaplatenie zmluvnej pokuty, nárok na náhradu škody, ktoré vznikli počas trvania zmluvy.',
      '7.5. Zánikom zmluvy nezaniká povinnosť objednávateľa uhradiť obstarávateľovi cenu za služby a cenu za obstaranie prepravy za zásielky vyexportované do systému prepravcu za príslušné obdobie kalendárneho mesiaca, a to za obdobie od prvého dňa príslušného kalendárneho mesiaca, v ktorom došlo k zániku zmluvy až do dňa zániku zmluvy.',
      '7.6. Ukončenie spolupráce bude po zániku zmluvy účtovne vysporiadané k poslednému kalendárnemu dňu v mesiaci.',
    ],
  },
  {
    heading: '8. OCHRANA OSOBNÝCH ÚDAJOV A ĎALŠÍCH OZNÁMENÝCH ÚDAJOV',
    items: [
      '8.1. Objednávateľ berie na vedomie, že jeho osobné údaje v rozsahu meno, priezvisko, bydlisko, alebo obchodné meno, sídlo, IČO, DIČ, telefónne číslo, mailová adresa, IP adresa, priradené prihlasovacie údaje, cookies, prihlasovacie údaje do online služieb, prihlasovacie a api údaje používateľa nevyhnutné pre dátové spojenie s prepravcom, vrátane požiadavky udania prehlásenia, že objednávateľ je osobou staršou ako 18 rokov, spracúva obstarávateľ za účelom plnenia povinnosti vyplývajúcich z tejto zmluvy, a v zmysle zákona č. 18/2018 Z.z. o ochrane osobných údajov, kedy sa osobitný súhlas objednávateľa ako dotknutej osoby nevyžaduje.',
      '8.2. Objednávateľ na účely zákona č. 18/2018 Z.z. vystupuje ako prevádzkovateľ preto je povinný zabezpečiť súhlas so spracovaním osobných údajov zo strany dotknutých osôb, ktorými sú príjemcovia alebo odosielatelia zásielok. Zároveň je prevádzkovateľ povinný oboznámiť dotknuté osoby s tým, že ich osobné údaje v rozsahu meno, priezvisko, bydlisko, telefónne číslo, mail, obchodné meno, sídlo, IČO, sú spracovávané obstarávateľom a prepravcom, pričom tieto dotknuté osoby musia byť upovedomené o tom, že prepravca je oprávnený vyžadovať na preukázanie identity aj predloženie dokladu totožnosti.',
      '8.3. Objednávateľ je povinný zabezpečiť od dotknutých osôb súhlas so spracovaním ich osobných údajov a zároveň tento osobitný súhlas dáva aj objednávateľ obstarávateľovi, a to súhlas so spracovaním osobných údajov a ich použitím za účelom vytvorenia databázy, s ich spracovaním pre vlastné potreby obstarávateľa na účely súvisiace so zmluvou, pre kontaktovanie príjemcov zásielok v súvislosti s marketingovým prieskumom a prieskumom ohľadne kvality služieb a spokojnosti zákazníkov, a to všetko v zmysle zákona č. 18/2018 Z.z. v platnom znení. Za účelom získania súhlasu dotknutých osôb so spracovaním ich osobných údajov na marketingové účely, je objednávateľ povinný pri každej a jeden dotknutej osobe vyznačiť, či udelila výslovný súhlas so spracovaním jej osobných údajov na tieto účely, prípadne či tento súhlas odvolala alebo neudelila vôbec. O týchto skutočnostiach je objednávateľ povinný bezprostredne informovať obstarávateľa, prípadne tieto informácie zadať priamo do systému Neoship. Bez ohľadu na dôvod, ak pri zásielke alebo na inom mieste nebude definovaný jednoznačný súhlas dotknutej osoby so spracovaním jej osobných údajov pre marketingové a prieskumné účely, obstarávateľ nesmie osobné údaje tejto dotknutej osoby na tieto účely použiť.',
      '8.4. Obstarávateľ spracováva osobné údaje po dobu trvania zmluvy. Zároveň osobné údaje dotknutých osôb – teda osôb, ktorým sú zásielky určené, alebo odosielatelia týchto zásielok, budú uchovávané v databáze obstarávateľa po dobu jedného roka odo dňa obstarania prepravy zásielky, pre prípadnú reklamáciu. Po uplynutí jedného roku budú tieto údaje anonymizované.',
      '8.5. Za účelom vytvárania štatistických údajov uchováva obstarávateľ osobné údaje objednávateľa po dobu piatich rokov od zániku zmluvy, pričom osobné údaje dotknutých osôb – adresátov alebo odosielateľov budú anonymizované. Po uplynutí tejto doby budú osobné údaje objednávateľa vymazané.',
      '8.6. Objednávateľ je povinný poskytnúť potrebnú súčinnosť obstarávateľovi pri spracovaní osobných údajov a v prípade potreby vyžiadať od dotknutých osôb ich výslovný a slobodný súhlas so spracovaním osobných údajov na vopred určený účel. Objednávateľ je povinný informovať bezodkladne obstarávateľa o požiadavkách dotknutých osôb týkajúcich sa zmeny ich osobných údajov, aktualizácie, opravy, výmazu alebo o odvolaní ich súhlasu so spracovaním osobných údajov.',
      '8.7. Obstarávateľ sa zaväzuje, že osobné údaje objednávateľa bude spracovávať a používať len v súlade so všeobecne záväznými právnymi predpismi a predovšetkým v súlade so zákonom č. 18/2018 Z.z., neposkytne údaje tretím osobám bez predchádzajúceho písomného súhlasu objednávateľa, okrem osôb, prostredníctvom ktorých zabezpečuje funkcionality systému a plnenie záväzku zo zmluvy, a pokiaľ mu túto povinnosť neukladá zákon. Objednávateľ je povinný upovedomiť dotknuté osoby, ktoré udelili súhlas so spracovaním ich osobných údajov na marketingové účely, že tieto údaje budú poskytnuté marketingovým spoločnostiam, ktoré tieto služby a prieskum zabezpečujú pre obstarávateľa. Obstarávateľ vyhlasuje, že osobné údaje objednávateľa budú spracúvané podľa pokynov objednávateľa a prostredníctvom informačných systémov obstarávateľa, pričom sa uplatňujú primerané technické, organizačné a personálne bezpečnostné opatrenia zodpovedajúce spôsobu spracúvania osobných údajov, osobné údaje budú spracovať výhradne oprávnené osoby, ktoré boli náležitým spôsobom poučené, a ktoré sú viazané povinnosťou mlčanlivosti.',
      '8.8. Objednávateľ udeľuje výslovný súhlas s oznámením osobných údajov a ďalších údajov uvedených v zmluve a vyplývajúcich z objednávok obstarania prepravy zásielok prepravcovi za účelom realizácie prepravy zásielok obstaranej obstarávateľom na základe zmluvy.',
      '8.9. Objednávateľ vyhlasuje, že disponuje súhlasom osôb so spracovaním ich osobných údajov, ktorým majú byť zásielky doručené a ktoré sú ako príjemcovia alebo odosielatelia zásielok zadané/zadávané do systému NEOSHIP. Objednávateľ sa zároveň zaväzuje získať súhlas týchto dotknutých osôb so spracovaním a využívaním ich osobných údajov za účelom ich kontaktovania a poskytovania marketingových služieb prípadne za účelom prieskumu ohľadne kvality poskytovaných služieb.',
      '8.10. Kontaktnou a zodpovednou osobou obstarávateľa vo vzťahu k spracúvaniu a ochrane osobných údajov je pán Mgr. Tomáš Záškvara, ktorého je možné kontaktovať na tel. čísle 0917 998 494 alebo emailom na zaskvara@neoship.sk. Tieto kontaktné údaje je objednávateľ oprávnený poskytnúť aj dotknutej osobe.',
      '8.11. Objednávateľ a dotknuté osoby majú právo byť informovaní o primeraných zárukách a bezpečnostných opatreniach prijatých za účelom ochrany osobných údajov, majú právo požadovať opravu alebo výmaz ich osobných údajov a zároveň sú oprávnení podať návrh na začatie konania o ochrane osobných údajov podľa §100 zákona č. 18/2018 Z.z.',
    ],
  },
  {
    heading: '9. ZÁVEREČNÉ USTANOVENIA',
    items: [
      '9.1. Zmluvné strany sa dohodli, že mailovú elektronickú korešpondenciu považujú za relevantný spôsob komunikácie, ktorý v plnom rozsahu nahrádza písomnú korešpondenciu. Elektronicky doručené podania zmluvných strán sú pre zmluvné strany záväzné a účinné.',
      '9.2. Zmeny a dodatky k týmto VOP musia mať písomnú formu. Akákoľvek zmena zmluvy musí byť písomná. Objednávateľ berie na vedomie, že prevod jeho práv a povinností zo zmluvy na tretiu osobu je možné uskutočniť len s predchádzajúcim písomným súhlasom obstarávateľa.',
      '9.3. Objednávateľ je povinný oznámiť obstarávateľovi akékoľvek zmeny údajov týkajúce sa samotného objednávateľa alebo osôb, ktorých sa plnenie zo zmluvy týka.',
      '9.4. Práva a povinnosti, ktoré nie sú upravené týmito VOP, sa spravujú príslušnými ustanoveniami zákona č. 513/1991 Zb. Obchodný zákonník v znení neskorších predpisov, zákona č. 40/1964 zb. Občiansky zákonník v znení neskorších predpisov, zákona č. 250/2007 Z.z. o ochrane spotrebiteľa a o zmene zákona Slovenskej národnej rady č. 372/1990 Zb. o priestupkoch v znení neskorších predpisov a zákona č. 18/2018 Z.z. o ochrane osobných údajov a inými právnymi predpismi platnými v Slovenskej republike.',
      '9.5. VOP sú platné a účinné od 14.5.2026',
    ],
  },
];

export const vopSignature = [
  'V MENE OBSTARÁVATEĽA:',
  'Meno: Ing. Juraj Balogh',
  'Konateľ spoločnosti',
  'Dátum: 14.5.2026',
  'Miesto: Bratislava - mestská časť Ružinov',
];
